services:
  - type: web
    name: leadgen-copilot-backend-v5
    env: node
    region: oregon
    buildCommand: cd backend && npm install --no-package-lock --legacy-peer-deps && npx puppeteer browsers install chrome
    startCommand: cd backend && NODE_OPTIONS="--openssl-legacy-provider" node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
      - key: PUPPETEER_ARGS
        value: --no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu,--headless=new
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: FRONTEND_URL
        value: https://leadgen-copilot-frontend-v5.onrender.com
      - key: RENDER
        value: "true"
    packages:
      - google-chrome-stable
    healthCheckPath: /health
    autoDeploy: true 